@startuml ClassDiagramm01
actor A1 #Green
entity E1
Boundary B1


A1 -> E1 : Отправляю запрос
E1 -> B1 : направляю на обработку
B1 -> E1 : Возвращаю обработанный файл
E1 -> A1 : Отправляю ответ

@enduml